### ISSUE TITLE
The sample slides is not replicable

### ISSUE THREAD

**Issue by eborbath** [kazuyanagimoto/quarto-slides-typst#3]
Hi,

I would like to ask you, how can I have 2, 3, 4, n number of pictures side by side on a slide? I was looking at the Multiple Columns setup, but I could not replicate it. I receive the following error in compiling that slide:

```
==> quarto preview clean.qmd --to clean-typst --no-watch-inputs --no-browse

pandoc 
  to: typst
  output-file: clean.typ
  standalone: true
  shift-heading-level-by: -1
  default-image-extension: svg
  wrap: none
  citeproc: false
  
metadata
  title: Quarto Clean Theme
  subtitle: A Minimalistic Theme for Quarto + Typst + Touying
  date: today
  date-format: long
  image: thumbnail.svg
  author:
    - name: Kazuharu Yanagimoto
      orcid: 0009-0007-1967-8304
      email: kazuharu.yanagimoto@cemfi.edu.es
      affiliations: CEMFI
  bibliography:
    - references.bib
  bibliographystyle: chicago-author-date
  font-paths:
    - static/fonts
  commands:
    - small-cite
  
[typst]: Compiling clean.typ to clean.pdf...error: label `<sec-last>` does not exist in the document
    ┌─ @preview/touying:0.5.2/src/utils.typ:127:13
    │
127 │       return (it.func())(..fields.values(), ..new-body)
    │              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

This experience also made me realize that your example slide-deck code is not replicable. When I run it, I get into an error with the regression table slide:

```
processing file: clean.qmd
  |.................................................   |  95% [unnamed-chunk-9]Error:
! The `regex` supplied `lines_insert()` did not match a unique line.
Backtrace:
  1. global .main()
  2. execute(...)
  3. rmarkdown::render(...)
  4. knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  5. knitr:::process_file(text, output)
     ...
 16. base::withRestarts(...)
 17. base (local) withRestartList(expr, restarts)
 18. base (local) withOneRestart(withRestartList(expr, restarts[-nr]), restarts[[nr]])
 19. base (local) docall(restart$handler, restartArgs)
 21. evaluate (local) fun(base::quote(`<smplErrr>`))
There were 50 or more warnings (use warnings() to see the first 50)
                                                                                                            


Quitting from lines 439-462 [unnamed-chunk-9] (clean.qmd)

Execution halted
```

If i delete that slide, the deck seems to compile, until yet another error:

```
==> quarto preview clean.qmd --to clean-typst --no-watch-inputs --no-browse



processing file: clean.qmd
                                                                                                            
output file: clean.knit.md

There were 50 or more warnings (use warnings() to see the first 50)
pandoc 
  to: typst
  output-file: clean.typ
  standalone: true
  default-image-extension: svg
  wrap: none
  citeproc: false
  
metadata
  title: Quarto Clean Theme
  subtitle: A Minimalistic Theme for Quarto + Typst + Touying
  date: today
  date-format: long
  image: thumbnail.svg
  author:
    - name: Kazuharu Yanagimoto
      orcid: 0009-0007-1967-8304
      email: kazuharu.yanagimoto@cemfi.edu.es
      affiliations: CEMFI
  bibliography:
    - references.bib
  bibliographystyle: chicago-author-date
  font-paths:
    - static/fonts
  commands:
    - small-cite
  
[typst]: Compiling clean.typ to clean.pdf...DONE

ERROR: Unable to read the extension 'clean'.
Please ensure that you provided the correct id and that the extension is installed.

Stack trace:
Please ensure that you provided the correct id and that the extension is installed.
    at loadExtension (file:///Applications/quarto/bin/quarto.js:42891:15)
    at Object.extension (file:///Applications/quarto/bin/quarto.js:42789:34)
    at readExtensionFormat (file:///Applications/quarto/bin/quarto.js:73141:50)
    at resolveFormats (file:///Applications/quarto/bin/quarto.js:73085:41)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async renderContexts (file:///Applications/quarto/bin/quarto.js:72910:21)
    at async Object.renderFormats (file:///Applications/quarto/bin/quarto.js:72954:22)
    at async readBaseInputIndex (file:///Applications/quarto/bin/quarto.js:74239:21)
    at async inputTargetIndex (file:///Applications/quarto/bin/quarto.js:74227:19)
    at async resolveInputTarget (file:///Applications/quarto/bin/quarto.js:74345:19)

```

**Comment by kazuyanagimoto** [comment]
I think your question is not related to the error, so I changed the title.

This error comes from the bug of `modelsummary` package, more precisely, its upstream package `tinytable`.
The bug has already been reported and solved in the development version of the package.  https://github.com/vincentarelbundock/modelsummary/issues/819
Please use GitHub version of `tinytable` for now.

For the original question, please re-raise the issue with a minimal replicable qmd-code. I don't get what you're trying to implement and why you got such an error.

**Comment by eborbath** [comment]
Thank you for getting back to me. Installing the github repo of ```modelsummary``` solves the first problem, but I still can't replicate the slides, and the original error stays the same. When I compile the whole code I get:

```

==> quarto preview clean.qmd --to clean-typst --no-watch-inputs --no-browse



processing file: clean.qmd
                                                                                                            
output file: clean.knit.md

There were 50 or more warnings (use warnings() to see the first 50)
pandoc 
  to: typst
  output-file: clean.typ
  standalone: true
  default-image-extension: svg
  wrap: none
  citeproc: false
  
metadata
  title: Quarto Clean Theme
  subtitle: A Minimalistic Theme for Quarto + Typst + Touying
  date: today
  date-format: long
  image: thumbnail.svg
  author:
    - name: Kazuharu Yanagimoto
      orcid: 0009-0007-1967-8304
      email: kazuharu.yanagimoto@cemfi.edu.es
      affiliations: CEMFI
  bibliography:
    - references.bib
  bibliographystyle: chicago-author-date
  font-paths:
    - static/fonts
  commands:
    - small-cite
  
[typst]: Compiling clean.typ to clean.pdf...DONE

ERROR: Unable to read the extension 'clean'.
Please ensure that you provided the correct id and that the extension is installed.

Stack trace:
Please ensure that you provided the correct id and that the extension is installed.
    at loadExtension (file:///Applications/quarto/bin/quarto.js:42891:15)
    at Object.extension (file:///Applications/quarto/bin/quarto.js:42789:34)
    at readExtensionFormat (file:///Applications/quarto/bin/quarto.js:73141:50)
    at resolveFormats (file:///Applications/quarto/bin/quarto.js:73085:41)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async renderContexts (file:///Applications/quarto/bin/quarto.js:72910:21)
    at async Object.renderFormats (file:///Applications/quarto/bin/quarto.js:72954:22)
    at async readBaseInputIndex (file:///Applications/quarto/bin/quarto.js:74239:21)
    at async inputTargetIndex (file:///Applications/quarto/bin/quarto.js:74227:19)
    at async resolveInputTarget (file:///Applications/quarto/bin/quarto.js:74345:19)
```

when I delete every other slides and only keep the multiple columns slide like this:

````md
---
title: Quarto Clean Theme
subtitle: A Minimalistic Theme for Quarto + Typst + Touying
date: today
date-format: long
image: thumbnail.svg
author:
  - name: Kazuharu Yanagimoto
    orcid: 0009-0007-1967-8304
    email: kazuharu.yanagimoto@cemfi.edu.es
    affiliations: CEMFI
format:
  clean-typst:
    bibliographystyle: "chicago-author-date"
    font-paths: ["static/fonts"]
    include-in-header: "custom.typ"
    commands: [small-cite]
execute: 
  echo: false
  warning: false
bibliography: [references.bib]
---

## Multiple Columns {#sec-multicolumns}

```{=typst}
#slide[
```

[Column 1]{.alert}

Here is a long sentence that will wrap onto the next line as it hits the column
width, and continue this way until it stops.

[[Back to main]{.button}](#sec-last)

```{=typst}
][
```

[Column 2]{.alert}

Some other text in another column.

A second paragraph.

```{=typst}
]
```

````

I get the following error:

```
==> quarto preview clean.qmd --to clean-typst --no-watch-inputs --no-browse

pandoc 
  to: typst
  output-file: clean.typ
  standalone: true
  shift-heading-level-by: -1
  default-image-extension: svg
  wrap: none
  citeproc: false
  
metadata
  title: Quarto Clean Theme
  subtitle: A Minimalistic Theme for Quarto + Typst + Touying
  date: today
  date-format: long
  image: thumbnail.svg
  author:
    - name: Kazuharu Yanagimoto
      orcid: 0009-0007-1967-8304
      email: kazuharu.yanagimoto@cemfi.edu.es
      affiliations: CEMFI
  bibliography:
    - references.bib
  bibliographystyle: chicago-author-date
  font-paths:
    - static/fonts
  commands:
    - small-cite
  
[typst]: Compiling clean.typ to clean.pdf...error: label `<sec-last>` does not exist in the document
    ┌─ @preview/touying:0.5.2/src/utils.typ:127:13
    │
127 │       return (it.func())(..fields.values(), ..new-body)
    │              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

**Comment by kazuyanagimoto** [comment]
According to the error, your code does not have `sec-last` section. The hyper-link is broken. You can delete the `[[Back to main]{.button}](#sec-last)` line or add a new section with labeled `sec-last`.


PS: I edited your question as the quarto code is wrapped by markdown syntax highlight. You can use four single quotations "````" in this case.
